- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - tldr
    - neofetch
    - xorg
    - kitty
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
   state: latest

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: latest

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: latest

- name: Install creative Apps
  pacman:
    name:
      - imagemagick
      - blender
    state: latest
