- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - tldr
    - neofetch
    - xorg
    - kitty
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
   state: latest

# configure git
- name: Configure the global git color usage
  git_config:
    name: color.ui
    scope: global
    value: auto
- name: Configure the global git username
  git_config:    
    name: user.name
    scope: global
    value: "Frank Elsinga"
- name: Configure the global git useremail
  git_config:    
    name: user.email
    scope: global
    value: "frank@elsinga.de"

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: latest

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: latest

- name: Install creative Apps
  pacman:
    name:
      - imagemagick
      - blender
    state: latest

- name: Uninstall unwanted Programms
  pacman:
    name: thunderbird
    state: absent
