- name: Enable pacman colourised output and verbose package lists
  replace:
    path: /etc/pacman.conf
    regexp: "{{ replace_var.regexp }}"
    replace: "{{ replace_var.replace }}"
  loop_control:
    loop_var: replace_var
  loop:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }

- name: Enable repositories
  replace:
    path: /etc/pacman.conf
    regexp: '^#\[{{ repo }}\]$\n^#Include\s+=\s+/etc/pacman.d/mirrorlist$'
    replace: '[{{ repo }}]\nInclude = /etc/pacman.d/mirrorlist'
  loop_control:
    loop_var: repo
  loop: '{{ pacman.repos }}'
  notify: Update pacman cache
  when: 'pacman.repos is defined'

- name: Ignore 'modified' group
  replace:
    path: /etc/pacman.conf
    regexp: '^#IgnoreGroup =$'
    replace: 'IgnoreGroup = modified'
