
- name: Install rcm for dotfiles management
  yay:
   name: 
    - rcm
   state: latest

- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ username }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  become: yes
  become_user: "{{ username }}"
  async: 60
  poll: 0

- name: Install user dotfiles
  command: rcup -d /home/{{ username}}/{{ dotfiles.destination}} {{ dotfiles.rcup_flags }}
  become: yes
  become_user: "{{ username }}" 
  async: 60
  poll: 0