- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - tldr
    - neofetch
    - xorg
    - kitty
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
   state: present

# configure git
- git_config:
  name: alias.st
  scope: global
  value: status
- git_config:
  name: color.ui
  scope: global
  value: auto
- git_config:    
  name: user.name
  scope: global
  value: "Frank Elsinga"
- git_config:    
  name: user.email
  scope: global
  value: "frank@elsinga.de"

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: present

- name: Install creative Apps
  pacman:
    name:
      - imagemagick
      - blender
    state: present

- name: Uninstall unwanted Programms
  pacman:
    name: thunderbird
    state: absent
