# bootstraping
- name: check for pacman updates
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install yay
  pacman:
    name: yay
    state: present
- include: pamac.yml

# install all programms and configure them
- name: Run installation scripts
  include: "{{ item }}"
  with_fileglob:
    - programms/*.yml

# configure the system
- name: Run system configuration skripts
  include: "{{ item }}"
  with_fileglob:
    - system_configureation/*.yml
